// Centralized icon exports for tree-shaking optimization
// Only import the icons we actually use to reduce bundle size

export {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Bell,
  Book,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  Clock,
  Copy,
  CreditCard,
  Crown,
  DollarSign,
  Dot,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  Filter,
  Globe,
  GripVertical,
  Heart,
  Link as LinkIcon,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize,
  Menu,
  MessageCircle,
  Mic,
  MicOff,
  Minimize,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  Package,
  Pause,
  PauseCircle,
  Phone,
  Play,
  PlayCircle,
  PlayIcon,
  Plus,
  Radio,
  RefreshCw,
  Reply,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  ShoppingCart,
  Smartphone,
  Star,
  Store,
  Trash2,
  User,
  Users,
  Video,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  X,
  XCircle,
  Zap,
} from 'lucide-react';

// Hint bundlers that lucide-react has no side-effects to improve treeshaking
export {}; // ensure this file is treated as a module

// Type for better intellisense
export type IconComponent = React.ComponentType<{
  className?: string;
  size?: number | string;
  strokeWidth?: number | string;
}>;